const IMGURLS = {
  heroImg: "assets/images/heroImg.jpg",
  car1: "assets/images/car1.png",
  car2: "assets/images/car2.png",
  car3: "assets/images/car3.png",
  naf: "assets/images/naf.png",
  img4_1: "assets/images/img4-1.png",
  img4_2: "assets/images/img4-2.png",
  img4_3: "assets/images/img4-3.png",
  calendar: "assets/images/calendarImg.png",
  calendar_mobile: "assets/images/calendarImg-mobile.png",
  address: "assets/images/addressImg.png",
  footer: "assets/images/footerImg.png",
  business: "assets/images/businessImg.png",
  img5: "assets/images/img5.png",
  person1: "assets/images/person1.jpg",
  person2: "assets/images/person2.jpg",
  person3: "assets/images/person3.jpg",
  person4: "assets/images/person4.jpg",
  person5: "assets/images/person5.jpg",
  person6: "assets/images/person6.jpg",
  person7: "assets/images/person7.jpg",
  person8: "assets/images/person8.jpg",
  stars: "assets/images/stars.png",
  fstars: "assets/images/5stars.svg",
};

export default IMGURLS;
