import IMGURLS from "./imgUrls";

const staticData = {
  tireData: [
    {
      title: "Tire Changes",
      description: "This is a service",
      type: "tire",
      price: 299,
      isAdditionalService: false,
    },
    {
      title: "Tire Hotel",
      description: "This is a service",
      type: "tire",
      price: 299,
      isAdditionalService: false,
    },
  ],
  tireAdditionalData: [
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "tire",
      price: 299,
      isAdditionalService: true,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "tire",
      price: 299,
      isAdditionalService: true,
    },
  ],
  careData: [
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: false,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: false,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: false,
    },
  ],
  careAdditionalData: [
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: true,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: true,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: true,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: true,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: true,
    },
    {
      title: "Extra car wash",
      description: "This is a service",
      type: "care",
      price: 299,
      isAdditionalService: true,
    },
  ],
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt inculpa qui officia deserunt mollit anim id est laborum.",
  list: [
    { title: "title-1", price: "KP-1" },
    { title: "title-2", price: "KP-2" },
    { title: "title-3", price: "KP-3" },
  ],
  imgUrl: "assets/images/img1.jpg",
  profileList: [
    {
      name: "Mattis Araya",
      image: IMGURLS.person1,
      role: "Tech lead",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Syver Kok",
      image: IMGURLS.person2,
      role: "Developer",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Tom-Arne Danielsen",
      image: IMGURLS.person3,
      role: "CEO & Founder",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Odin Alveng",
      image: IMGURLS.person4,
      role: "CCO & Co-founder",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Joachim Rathke",
      image: IMGURLS.person5,
      role: "CPO & Co-founder",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Stian Grimsgaard",
      image: IMGURLS.person6,
      role: "CTO & Co-founder",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Carl Watkins",
      image: IMGURLS.person7,
      role: "Head of detailing",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
    {
      name: "Andrew Morrow",
      image: IMGURLS.person8,
      role: "Detailer",
      email: "email",
      linkedin: "linkedin",
      phone: "phone",
    },
  ],
};

export default staticData;
